language: python

python:
  - "3.6"

install:
  - conda install -c conda-forge -c astra-toolbox -c numba -c anaconda astra-toolbox=1.8.3 jupyterlab jupyter_client=7.1.0 jupyter_server=1.13.1 numpy scipy matplotlib scikit-image numba cython pywavelets jupyterlab_widgets ipympl ipywidgets
  - pip install libertem --ignore-installed --user
  - pip install codecov
  - pip install pytest-cov

script:
  - py.test --cov-report=xml --cov=deeptabular tests

after_success:
- codecov